package com.compomics.spectrawl.gui.view;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JList;
import javax.swing.JTextField;

/**
 *
 * @author niels
 */
public class FilterConfigDialog extends javax.swing.JDialog {

    /**
     * Creates new form FilterConfigDialog
     */
    public FilterConfigDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);        
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
        setLocationRelativeTo(parent);
    }

    public JButton getAddMzDeltaButton() {
        return addMzDeltaButton;
    }

    public JTextField getAddMzDeltaTextField() {
        return addMzDeltaTextField;
    }

    public JButton getAddMzRatioButton() {
        return addMzRatioButton;
    }

    public JTextField getAddMzRatioTextField() {
        return addMzRatioTextField;
    }

    public JTextField getIntensityThresholdTextField() {
        return intensityThresholdTextField;
    }

    public JList getMzDeltaFilterList() {
        return mzDeltaFilterList;
    }

    public JList getMzRatioFilterList() {
        return mzRatioFilterList;
    }

    public JTextField getMzToleranceTextField() {
        return mzToleranceTextField;
    }

    public JButton getRemoveMzDeltaButton() {
        return removeMzDeltaButton;
    }

    public JButton getRemoveMzRatioButton() {
        return removeMzRatioButton;
    }

    public JTextField getWinsorConstantTextField() {
        return winsorConstantTextField;
    }

    public JTextField getWinsorConvergenceCriterionTextField() {
        return winsorConvergenceCriterionTextField;
    }

    public JCheckBox getWinsorFilterCheckBox() {
        return winsorFilterCheckBox;
    }

    public JTextField getWinsorOutlierLimitTextField() {
        return winsorOutlierLimitTextField;
    }        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        FilterConfigTabbedPane = new javax.swing.JTabbedPane();
        mzRatioFilterPanel = new javax.swing.JPanel();
        peakMzRatioFilterPanel = new javax.swing.JPanel();
        peakMzRatioFilterScrollPane = new javax.swing.JScrollPane();
        mzRatioFilterList = new javax.swing.JList();
        addMzRatioLabel = new javax.swing.JLabel();
        addMzRatioTextField = new javax.swing.JTextField();
        addMzRatioButton = new javax.swing.JButton();
        removeMzRatioButton = new javax.swing.JButton();
        mzToleranceLabel = new javax.swing.JLabel();
        mzToleranceTextField = new javax.swing.JTextField();
        mzDeltaFilterPanel = new javax.swing.JPanel();
        mzDeltaFilterScrollPane = new javax.swing.JScrollPane();
        mzDeltaFilterList = new javax.swing.JList();
        addMzDeltaLabel = new javax.swing.JLabel();
        addMzDeltaTextField = new javax.swing.JTextField();
        addMzDeltaButton = new javax.swing.JButton();
        removeMzDeltaButton = new javax.swing.JButton();
        intensityThresholdLabel = new javax.swing.JLabel();
        intensityThresholdTextField = new javax.swing.JTextField();
        noiseFilterPanel = new javax.swing.JPanel();
        winsorFilterCheckBox = new javax.swing.JCheckBox();
        winsorConstantLabel = new javax.swing.JLabel();
        winsorConstantTextField = new javax.swing.JTextField();
        winsorConvergenceCriterionLabel = new javax.swing.JLabel();
        winsorConvergenceCriterionTextField = new javax.swing.JTextField();
        winsorOutlierLimitLabel = new javax.swing.JLabel();
        winsorOutlierLimitTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        mzRatioFilterPanel.setOpaque(false);
        mzRatioFilterPanel.setLayout(new java.awt.GridBagLayout());

        peakMzRatioFilterPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("M/Z ratio filter"));
        peakMzRatioFilterPanel.setMinimumSize(new java.awt.Dimension(4, 4));
        peakMzRatioFilterPanel.setOpaque(false);
        peakMzRatioFilterPanel.setPreferredSize(new java.awt.Dimension(4, 4));

        peakMzRatioFilterScrollPane.setViewportView(mzRatioFilterList);

        addMzRatioLabel.setText("M/Z ratio");

        addMzRatioTextField.setPreferredSize(new java.awt.Dimension(6, 25));

        addMzRatioButton.setText("add");
        addMzRatioButton.setMaximumSize(new java.awt.Dimension(97, 23));
        addMzRatioButton.setMinimumSize(new java.awt.Dimension(97, 23));
        addMzRatioButton.setPreferredSize(new java.awt.Dimension(97, 23));

        removeMzRatioButton.setText("remove");
        removeMzRatioButton.setMaximumSize(new java.awt.Dimension(97, 23));
        removeMzRatioButton.setMinimumSize(new java.awt.Dimension(97, 23));
        removeMzRatioButton.setPreferredSize(new java.awt.Dimension(97, 23));

        mzToleranceLabel.setText("M/Z tolerance");

        mzToleranceTextField.setPreferredSize(new java.awt.Dimension(6, 25));

        javax.swing.GroupLayout peakMzRatioFilterPanelLayout = new javax.swing.GroupLayout(peakMzRatioFilterPanel);
        peakMzRatioFilterPanel.setLayout(peakMzRatioFilterPanelLayout);
        peakMzRatioFilterPanelLayout.setHorizontalGroup(
            peakMzRatioFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(peakMzRatioFilterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(peakMzRatioFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(peakMzRatioFilterPanelLayout.createSequentialGroup()
                        .addComponent(addMzRatioButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeMzRatioButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(peakMzRatioFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(peakMzRatioFilterPanelLayout.createSequentialGroup()
                            .addComponent(mzToleranceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mzToleranceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(peakMzRatioFilterScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(peakMzRatioFilterPanelLayout.createSequentialGroup()
                            .addComponent(addMzRatioLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addMzRatioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        peakMzRatioFilterPanelLayout.setVerticalGroup(
            peakMzRatioFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(peakMzRatioFilterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(peakMzRatioFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mzToleranceLabel)
                    .addComponent(mzToleranceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(peakMzRatioFilterScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(peakMzRatioFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addMzRatioLabel)
                    .addComponent(addMzRatioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(peakMzRatioFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeMzRatioButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addMzRatioButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(2, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        mzRatioFilterPanel.add(peakMzRatioFilterPanel, gridBagConstraints);

        mzDeltaFilterPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("M/Z delta filter"));
        mzDeltaFilterPanel.setMinimumSize(new java.awt.Dimension(4, 4));
        mzDeltaFilterPanel.setOpaque(false);
        mzDeltaFilterPanel.setPreferredSize(new java.awt.Dimension(4, 4));

        mzDeltaFilterScrollPane.setViewportView(mzDeltaFilterList);

        addMzDeltaLabel.setText("M/Z delta");

        addMzDeltaTextField.setPreferredSize(new java.awt.Dimension(6, 25));

        addMzDeltaButton.setText("add");
        addMzDeltaButton.setMaximumSize(new java.awt.Dimension(97, 23));
        addMzDeltaButton.setMinimumSize(new java.awt.Dimension(97, 23));
        addMzDeltaButton.setPreferredSize(new java.awt.Dimension(97, 23));

        removeMzDeltaButton.setText("remove");
        removeMzDeltaButton.setMaximumSize(new java.awt.Dimension(97, 23));
        removeMzDeltaButton.setMinimumSize(new java.awt.Dimension(97, 23));
        removeMzDeltaButton.setPreferredSize(new java.awt.Dimension(97, 23));

        intensityThresholdLabel.setText("Intensity threshold");

        intensityThresholdTextField.setPreferredSize(new java.awt.Dimension(6, 25));

        javax.swing.GroupLayout mzDeltaFilterPanelLayout = new javax.swing.GroupLayout(mzDeltaFilterPanel);
        mzDeltaFilterPanel.setLayout(mzDeltaFilterPanelLayout);
        mzDeltaFilterPanelLayout.setHorizontalGroup(
            mzDeltaFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mzDeltaFilterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mzDeltaFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(mzDeltaFilterPanelLayout.createSequentialGroup()
                        .addComponent(intensityThresholdLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(intensityThresholdTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mzDeltaFilterPanelLayout.createSequentialGroup()
                        .addComponent(addMzDeltaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addMzDeltaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(mzDeltaFilterScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mzDeltaFilterPanelLayout.createSequentialGroup()
                        .addComponent(addMzDeltaButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeMzDeltaButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        mzDeltaFilterPanelLayout.setVerticalGroup(
            mzDeltaFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mzDeltaFilterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mzDeltaFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(intensityThresholdLabel)
                    .addComponent(intensityThresholdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(mzDeltaFilterScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(mzDeltaFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addMzDeltaLabel)
                    .addComponent(addMzDeltaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mzDeltaFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeMzDeltaButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addMzDeltaButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(2, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        mzRatioFilterPanel.add(mzDeltaFilterPanel, gridBagConstraints);

        FilterConfigTabbedPane.addTab("Spectrum Filter Settings", mzRatioFilterPanel);

        noiseFilterPanel.setOpaque(false);

        winsorFilterCheckBox.setText("do winsorisation filtering");

        winsorConstantLabel.setText("winsorisation constant");

        winsorConstantTextField.setEnabled(false);
        winsorConstantTextField.setPreferredSize(new java.awt.Dimension(60, 25));

        winsorConvergenceCriterionLabel.setText("winsorisation convergence criterion");

        winsorConvergenceCriterionTextField.setEnabled(false);
        winsorConvergenceCriterionTextField.setMinimumSize(new java.awt.Dimension(6, 25));
        winsorConvergenceCriterionTextField.setPreferredSize(new java.awt.Dimension(60, 25));

        winsorOutlierLimitLabel.setText("winsorisation outlier limit");

        winsorOutlierLimitTextField.setEnabled(false);
        winsorOutlierLimitTextField.setMinimumSize(new java.awt.Dimension(6, 25));
        winsorOutlierLimitTextField.setPreferredSize(new java.awt.Dimension(60, 25));

        javax.swing.GroupLayout noiseFilterPanelLayout = new javax.swing.GroupLayout(noiseFilterPanel);
        noiseFilterPanel.setLayout(noiseFilterPanelLayout);
        noiseFilterPanelLayout.setHorizontalGroup(
            noiseFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
            .addGroup(noiseFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(noiseFilterPanelLayout.createSequentialGroup()
                    .addGap(0, 116, Short.MAX_VALUE)
                    .addGroup(noiseFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(winsorFilterCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(noiseFilterPanelLayout.createSequentialGroup()
                            .addComponent(winsorConstantLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(5, 5, 5)
                            .addComponent(winsorConstantTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(noiseFilterPanelLayout.createSequentialGroup()
                            .addComponent(winsorConvergenceCriterionLabel)
                            .addGap(5, 5, 5)
                            .addComponent(winsorConvergenceCriterionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(noiseFilterPanelLayout.createSequentialGroup()
                            .addComponent(winsorOutlierLimitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(5, 5, 5)
                            .addComponent(winsorOutlierLimitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 117, Short.MAX_VALUE)))
        );
        noiseFilterPanelLayout.setVerticalGroup(
            noiseFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 293, Short.MAX_VALUE)
            .addGroup(noiseFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(noiseFilterPanelLayout.createSequentialGroup()
                    .addGap(0, 82, Short.MAX_VALUE)
                    .addComponent(winsorFilterCheckBox)
                    .addGap(10, 10, 10)
                    .addGroup(noiseFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(noiseFilterPanelLayout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addComponent(winsorConstantLabel))
                        .addComponent(winsorConstantTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addGroup(noiseFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(noiseFilterPanelLayout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addComponent(winsorConvergenceCriterionLabel))
                        .addComponent(winsorConvergenceCriterionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addGroup(noiseFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(noiseFilterPanelLayout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addComponent(winsorOutlierLimitLabel))
                        .addComponent(winsorOutlierLimitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 83, Short.MAX_VALUE)))
        );

        FilterConfigTabbedPane.addTab("Spectrum Noise Filter Settings", noiseFilterPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(FilterConfigTabbedPane))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 321, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(FilterConfigTabbedPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane FilterConfigTabbedPane;
    private javax.swing.JButton addMzDeltaButton;
    private javax.swing.JLabel addMzDeltaLabel;
    private javax.swing.JTextField addMzDeltaTextField;
    private javax.swing.JButton addMzRatioButton;
    private javax.swing.JLabel addMzRatioLabel;
    private javax.swing.JTextField addMzRatioTextField;
    private javax.swing.JLabel intensityThresholdLabel;
    private javax.swing.JTextField intensityThresholdTextField;
    private javax.swing.JList mzDeltaFilterList;
    private javax.swing.JPanel mzDeltaFilterPanel;
    private javax.swing.JScrollPane mzDeltaFilterScrollPane;
    private javax.swing.JList mzRatioFilterList;
    private javax.swing.JPanel mzRatioFilterPanel;
    private javax.swing.JLabel mzToleranceLabel;
    private javax.swing.JTextField mzToleranceTextField;
    private javax.swing.JPanel noiseFilterPanel;
    private javax.swing.JPanel peakMzRatioFilterPanel;
    private javax.swing.JScrollPane peakMzRatioFilterScrollPane;
    private javax.swing.JButton removeMzDeltaButton;
    private javax.swing.JButton removeMzRatioButton;
    private javax.swing.JLabel winsorConstantLabel;
    private javax.swing.JTextField winsorConstantTextField;
    private javax.swing.JLabel winsorConvergenceCriterionLabel;
    private javax.swing.JTextField winsorConvergenceCriterionTextField;
    private javax.swing.JCheckBox winsorFilterCheckBox;
    private javax.swing.JLabel winsorOutlierLimitLabel;
    private javax.swing.JTextField winsorOutlierLimitTextField;
    // End of variables declaration//GEN-END:variables
}
