/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.compomics.spectrawl.view;

import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author niels
 */
public class ExperimentBinsPanel extends javax.swing.JPanel {

    /**
     * Creates new form ExperimentBinsPanel
     */
    public ExperimentBinsPanel() {
        initComponents();
    }

    public JPanel getCountChartParentPanel() {
        return countChartParentPanel;
    }

    public JPanel getIntensityChartParentPanel() {
        return intensityChartParentPanel;
    }
    
    public JLabel getExperimentInfoLabel() {
        return experimentInfoLabel;
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        experimentInfoLabelPanel = new javax.swing.JPanel();
        experimentInfoLabel = new javax.swing.JLabel();
        chartsTabbedPane = new javax.swing.JTabbedPane();
        intensityChartParentPanel = new javax.swing.JPanel();
        countChartParentPanel = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(20, 20));
        setPreferredSize(new java.awt.Dimension(20, 20));
        setLayout(new java.awt.GridBagLayout());

        experimentInfoLabelPanel.setLayout(new java.awt.GridBagLayout());

        experimentInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        experimentInfoLabelPanel.add(experimentInfoLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(experimentInfoLabelPanel, gridBagConstraints);

        chartsTabbedPane.setMinimumSize(new java.awt.Dimension(20, 20));
        chartsTabbedPane.setPreferredSize(new java.awt.Dimension(20, 20));

        intensityChartParentPanel.setLayout(new java.awt.GridBagLayout());
        chartsTabbedPane.addTab("intensities chart", intensityChartParentPanel);

        countChartParentPanel.setLayout(new java.awt.GridBagLayout());
        chartsTabbedPane.addTab("count chart", countChartParentPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(chartsTabbedPane, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane chartsTabbedPane;
    private javax.swing.JPanel countChartParentPanel;
    private javax.swing.JLabel experimentInfoLabel;
    private javax.swing.JPanel experimentInfoLabelPanel;
    private javax.swing.JPanel intensityChartParentPanel;
    // End of variables declaration//GEN-END:variables
}
