/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.compomics.spectrawl.gui.view;

import java.awt.Color;
import java.awt.Frame;
import javax.swing.JMenuItem;
import javax.swing.JPanel;

/**
 *
 * @author niels
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form SpectrawlFrame
     */
    public MainFrame() {
        initComponents();
        this.getContentPane().setBackground(new Color(255, 255, 255));
        setLocationRelativeTo(null);
        setExtendedState(Frame.MAXIMIZED_BOTH);
        setVisible(true);
    }

    public JPanel getExperimentBinsParentPanel() {
        return experimentBinsParentPanel;
    }

    public JPanel getExperimentLoaderParentPanel() {
        return experimentLoaderParentPanel;
    }

    public JMenuItem getExitMenuItem() {
        return exitMenuItem;
    }

    public JMenuItem getFilterSettingsMenuItem() {
        return filterSettingsMenuItem;
    }        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        experimentLoaderParentPanel = new javax.swing.JPanel();
        experimentBinsParentPanel = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        filterSettingsMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Spectrawl");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(10, 10));
        setPreferredSize(new java.awt.Dimension(900, 700));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 5, 0};
        layout.rowHeights = new int[] {0, 5, 0};
        getContentPane().setLayout(layout);

        experimentLoaderParentPanel.setBackground(new java.awt.Color(255, 255, 255));
        experimentLoaderParentPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        experimentLoaderParentPanel.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.weighty = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        getContentPane().add(experimentLoaderParentPanel, gridBagConstraints);

        experimentBinsParentPanel.setBackground(new java.awt.Color(255, 255, 255));
        experimentBinsParentPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        experimentBinsParentPanel.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.weighty = 0.7;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        getContentPane().add(experimentBinsParentPanel, gridBagConstraints);

        fileMenu.setText("File");

        exitMenuItem.setText("Exit");
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setText("Edit");

        filterSettingsMenuItem.setText("Filter Settings");
        editMenu.add(filterSettingsMenuItem);

        menuBar.add(editMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JPanel experimentBinsParentPanel;
    private javax.swing.JPanel experimentLoaderParentPanel;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem filterSettingsMenuItem;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables
}
