/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.compomics.spectrawl.gui.view;

import com.compomics.spectrawl.gui.controller.MainController;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author niels
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form SpectrawlFrame
     */
    public MainFrame() {
        initComponents();    
        this.getContentPane().setBackground(new Color(255, 255, 255));
        setLocationRelativeTo(null);
        setVisible(true);
    }

    public JPanel getAnalyzeFilterParentPanel() {
        return analyzeFilterParentPanel;
    }

    public JPanel getExperimentBinsParentPanel() {
        return experimentBinsParentPanel;
    }

    public JPanel getExperimentLoaderParentPanel() {
        return experimentLoaderParentPanel;
    }

    public JPanel getProcessFilterParentPanel() {
        return processFilterParentPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        experimentLoaderParentPanel = new javax.swing.JPanel();
        filtersTabbedPane = new javax.swing.JTabbedPane();
        analyzeFilterParentPanel = new javax.swing.JPanel();
        processFilterParentPanel = new javax.swing.JPanel();
        experimentBinsParentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Spectrawl");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(10, 10));
        setPreferredSize(new java.awt.Dimension(900, 700));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 5, 0};
        layout.rowHeights = new int[] {0, 5, 0};
        getContentPane().setLayout(layout);

        experimentLoaderParentPanel.setBackground(new java.awt.Color(255, 255, 255));
        experimentLoaderParentPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        experimentLoaderParentPanel.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.weighty = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        getContentPane().add(experimentLoaderParentPanel, gridBagConstraints);

        filtersTabbedPane.setBackground(new java.awt.Color(255, 255, 255));
        filtersTabbedPane.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        filtersTabbedPane.setMinimumSize(new java.awt.Dimension(4, 4));
        filtersTabbedPane.setOpaque(true);
        filtersTabbedPane.setPreferredSize(new java.awt.Dimension(4, 4));

        analyzeFilterParentPanel.setLayout(new java.awt.GridBagLayout());
        filtersTabbedPane.addTab("analyze filter", analyzeFilterParentPanel);

        processFilterParentPanel.setLayout(new java.awt.GridBagLayout());
        filtersTabbedPane.addTab("process filter", processFilterParentPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        getContentPane().add(filtersTabbedPane, gridBagConstraints);

        experimentBinsParentPanel.setBackground(new java.awt.Color(255, 255, 255));
        experimentBinsParentPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        experimentBinsParentPanel.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.weighty = 0.7;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        getContentPane().add(experimentBinsParentPanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel analyzeFilterParentPanel;
    private javax.swing.JPanel experimentBinsParentPanel;
    private javax.swing.JPanel experimentLoaderParentPanel;
    private javax.swing.JTabbedPane filtersTabbedPane;
    private javax.swing.JPanel processFilterParentPanel;
    // End of variables declaration//GEN-END:variables
}
