package com.compomics.spectrawl.gui.view;

import java.awt.Color;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JList;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author niels
 */
public class MassFilterDialog extends javax.swing.JDialog {

    /**
     * Creates new form FilterConfigDialog
     */
    public MassFilterDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);        
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
        setLocationRelativeTo(parent);
    }

    public JButton getAddMassButton() {
        return addMassButton;
    }

    public JTextField getAddMassTextField() {
        return addMassTextField;
    }

    public JButton getAddPrecRelMassButton() {
        return addPrecRelMassButton;
    }

    public JTextField getAddPrecRelMassTextField() {
        return addPrecRelMassTextField;
    }

    public JRadioButton getAndRadioButton() {
        return andRadioButton;
    }

    public ButtonGroup getFilterTypeRadioButtonGroup() {
        return filterTypeRadioButtonGroup;
    }

    public JList getMassFilterList() {
        return massFilterList;
    }

    public JTextField getMassToleranceTextField() {
        return massToleranceTextField;
    }

    public JRadioButton getOrRadioButton() {
        return orRadioButton;
    }

    public JRadioButton getPrecRelAndRadioButton() {
        return precRelAndRadioButton;
    }

    public ButtonGroup getPrecRelFilterTypeRadioButtonGroup() {
        return precRelFilterTypeRadioButtonGroup;
    }

    public JList getPrecRelMassFilterList() {
        return precRelMassFilterList;
    }

    public JTextField getPrecRelMassToleranceTextField() {
        return precRelMassToleranceTextField;
    }

    public JRadioButton getPrecRelOrRadioButton() {
        return precRelOrRadioButton;
    }

    public JButton getRemoveMassButton() {
        return removeMassButton;
    }

    public JButton getRemovePrecRelMassButton() {
        return removePrecRelMassButton;
    }

    public JTextField getWinsorConstantTextField() {
        return winsorConstantTextField;
    }

    public JTextField getWinsorConvergenceCriterionTextField() {
        return winsorConvergenceCriterionTextField;
    }

    public JCheckBox getWinsorFilterCheckBox() {
        return winsorFilterCheckBox;
    }

    public JTextField getWinsorOutlierLimitTextField() {
        return winsorOutlierLimitTextField;
    }          

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filterTypeRadioButtonGroup = new javax.swing.ButtonGroup();
        precRelFilterTypeRadioButtonGroup = new javax.swing.ButtonGroup();
        FilteSettingsTabbedPane = new javax.swing.JTabbedPane();
        noiseFilterPanel = new javax.swing.JPanel();
        winsorFilterCheckBox = new javax.swing.JCheckBox();
        winsorConstantLabel = new javax.swing.JLabel();
        winsorConstantTextField = new javax.swing.JTextField();
        winsorConvergenceCriterionLabel = new javax.swing.JLabel();
        winsorConvergenceCriterionTextField = new javax.swing.JTextField();
        winsorOutlierLimitLabel = new javax.swing.JLabel();
        winsorOutlierLimitTextField = new javax.swing.JTextField();
        massFilterPanel = new javax.swing.JPanel();
        massFilterScrollPane = new javax.swing.JScrollPane();
        massFilterList = new javax.swing.JList();
        addMassLabel = new javax.swing.JLabel();
        addMassTextField = new javax.swing.JTextField();
        addMassButton = new javax.swing.JButton();
        removeMassButton = new javax.swing.JButton();
        massToleranceLabel = new javax.swing.JLabel();
        massToleranceTextField = new javax.swing.JTextField();
        filterTypeLabel = new javax.swing.JLabel();
        andRadioButton = new javax.swing.JRadioButton();
        orRadioButton = new javax.swing.JRadioButton();
        precRelMassFilterPanel = new javax.swing.JPanel();
        precRelMassFilterScrollPane = new javax.swing.JScrollPane();
        precRelMassFilterList = new javax.swing.JList();
        addPrecRelMassLabel = new javax.swing.JLabel();
        addPrecRelMassTextField = new javax.swing.JTextField();
        addPrecRelMassButton = new javax.swing.JButton();
        removePrecRelMassButton = new javax.swing.JButton();
        precRelMassToleranceLabel = new javax.swing.JLabel();
        precRelMassToleranceTextField = new javax.swing.JTextField();
        precRelFilterTypeLabel = new javax.swing.JLabel();
        precRelAndRadioButton = new javax.swing.JRadioButton();
        precRelOrRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        noiseFilterPanel.setOpaque(false);

        winsorFilterCheckBox.setText("do winsorisation filtering");

        winsorConstantLabel.setText("winsorisation constant");

        winsorConstantTextField.setEnabled(false);
        winsorConstantTextField.setPreferredSize(new java.awt.Dimension(60, 25));

        winsorConvergenceCriterionLabel.setText("winsorisation convergence criterion");

        winsorConvergenceCriterionTextField.setEnabled(false);
        winsorConvergenceCriterionTextField.setMinimumSize(new java.awt.Dimension(6, 25));
        winsorConvergenceCriterionTextField.setPreferredSize(new java.awt.Dimension(60, 25));

        winsorOutlierLimitLabel.setText("winsorisation outlier limit");

        winsorOutlierLimitTextField.setEnabled(false);
        winsorOutlierLimitTextField.setMinimumSize(new java.awt.Dimension(6, 25));
        winsorOutlierLimitTextField.setPreferredSize(new java.awt.Dimension(60, 25));

        javax.swing.GroupLayout noiseFilterPanelLayout = new javax.swing.GroupLayout(noiseFilterPanel);
        noiseFilterPanel.setLayout(noiseFilterPanelLayout);
        noiseFilterPanelLayout.setHorizontalGroup(
            noiseFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noiseFilterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(noiseFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(noiseFilterPanelLayout.createSequentialGroup()
                        .addComponent(winsorConvergenceCriterionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                        .addComponent(winsorConvergenceCriterionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(noiseFilterPanelLayout.createSequentialGroup()
                        .addComponent(winsorFilterCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(noiseFilterPanelLayout.createSequentialGroup()
                        .addComponent(winsorConstantLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(winsorConstantTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(noiseFilterPanelLayout.createSequentialGroup()
                        .addComponent(winsorOutlierLimitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(winsorOutlierLimitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        noiseFilterPanelLayout.setVerticalGroup(
            noiseFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noiseFilterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(winsorFilterCheckBox)
                .addGap(18, 18, 18)
                .addGroup(noiseFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(winsorConstantLabel)
                    .addComponent(winsorConstantTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(noiseFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(winsorConvergenceCriterionLabel)
                    .addComponent(winsorConvergenceCriterionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(noiseFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(winsorOutlierLimitLabel)
                    .addComponent(winsorOutlierLimitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(157, Short.MAX_VALUE))
        );

        FilteSettingsTabbedPane.addTab("Noise filter settings", noiseFilterPanel);

        massFilterPanel.setOpaque(false);

        massFilterScrollPane.setViewportView(massFilterList);

        addMassLabel.setText("Mass");

        addMassTextField.setPreferredSize(new java.awt.Dimension(6, 25));

        addMassButton.setText("add");
        addMassButton.setMaximumSize(new java.awt.Dimension(97, 23));
        addMassButton.setMinimumSize(new java.awt.Dimension(97, 23));
        addMassButton.setPreferredSize(new java.awt.Dimension(97, 23));

        removeMassButton.setText("remove");
        removeMassButton.setMaximumSize(new java.awt.Dimension(97, 23));
        removeMassButton.setMinimumSize(new java.awt.Dimension(97, 23));
        removeMassButton.setPreferredSize(new java.awt.Dimension(97, 23));

        massToleranceLabel.setText("Mass tolerance");

        massToleranceTextField.setPreferredSize(new java.awt.Dimension(6, 25));

        filterTypeLabel.setText("Filter type");

        filterTypeRadioButtonGroup.add(andRadioButton);
        andRadioButton.setText("and");

        filterTypeRadioButtonGroup.add(orRadioButton);
        orRadioButton.setText("or");

        javax.swing.GroupLayout massFilterPanelLayout = new javax.swing.GroupLayout(massFilterPanel);
        massFilterPanel.setLayout(massFilterPanelLayout);
        massFilterPanelLayout.setHorizontalGroup(
            massFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(massFilterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(massFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(massFilterPanelLayout.createSequentialGroup()
                        .addComponent(massToleranceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(massToleranceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(massFilterScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(massFilterPanelLayout.createSequentialGroup()
                        .addComponent(addMassLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addMassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(massFilterPanelLayout.createSequentialGroup()
                        .addComponent(addMassButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeMassButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(massFilterPanelLayout.createSequentialGroup()
                        .addComponent(filterTypeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(andRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(orRadioButton)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        massFilterPanelLayout.setVerticalGroup(
            massFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(massFilterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(massFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(massToleranceLabel)
                    .addComponent(massToleranceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(massFilterScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(massFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addMassLabel)
                    .addComponent(addMassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(massFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addMassButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeMassButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(massFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filterTypeLabel)
                    .addComponent(andRadioButton)
                    .addComponent(orRadioButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        FilteSettingsTabbedPane.addTab("Mass ratio filter settings", massFilterPanel);

        precRelMassFilterPanel.setOpaque(false);

        precRelMassFilterScrollPane.setViewportView(precRelMassFilterList);

        addPrecRelMassLabel.setText("Mass");

        addPrecRelMassTextField.setPreferredSize(new java.awt.Dimension(6, 25));

        addPrecRelMassButton.setText("add");
        addPrecRelMassButton.setMaximumSize(new java.awt.Dimension(97, 23));
        addPrecRelMassButton.setMinimumSize(new java.awt.Dimension(97, 23));
        addPrecRelMassButton.setPreferredSize(new java.awt.Dimension(97, 23));

        removePrecRelMassButton.setText("remove");
        removePrecRelMassButton.setMaximumSize(new java.awt.Dimension(97, 23));
        removePrecRelMassButton.setMinimumSize(new java.awt.Dimension(97, 23));
        removePrecRelMassButton.setPreferredSize(new java.awt.Dimension(97, 23));

        precRelMassToleranceLabel.setText("Mass tolerance");

        precRelMassToleranceTextField.setPreferredSize(new java.awt.Dimension(6, 25));

        precRelFilterTypeLabel.setText("Filter type");

        filterTypeRadioButtonGroup.add(precRelAndRadioButton);
        precRelAndRadioButton.setText("and");

        filterTypeRadioButtonGroup.add(precRelOrRadioButton);
        precRelOrRadioButton.setText("or");

        javax.swing.GroupLayout precRelMassFilterPanelLayout = new javax.swing.GroupLayout(precRelMassFilterPanel);
        precRelMassFilterPanel.setLayout(precRelMassFilterPanelLayout);
        precRelMassFilterPanelLayout.setHorizontalGroup(
            precRelMassFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(precRelMassFilterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(precRelMassFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(precRelMassFilterPanelLayout.createSequentialGroup()
                        .addComponent(precRelMassToleranceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(precRelMassToleranceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(precRelMassFilterScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(precRelMassFilterPanelLayout.createSequentialGroup()
                        .addComponent(addPrecRelMassLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addPrecRelMassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(precRelMassFilterPanelLayout.createSequentialGroup()
                        .addComponent(addPrecRelMassButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removePrecRelMassButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(precRelMassFilterPanelLayout.createSequentialGroup()
                        .addComponent(precRelFilterTypeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(precRelAndRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(precRelOrRadioButton)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        precRelMassFilterPanelLayout.setVerticalGroup(
            precRelMassFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(precRelMassFilterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(precRelMassFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precRelMassToleranceLabel)
                    .addComponent(precRelMassToleranceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(precRelMassFilterScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(precRelMassFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPrecRelMassLabel)
                    .addComponent(addPrecRelMassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(precRelMassFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPrecRelMassButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removePrecRelMassButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(precRelMassFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precRelFilterTypeLabel)
                    .addComponent(precRelAndRadioButton)
                    .addComponent(precRelOrRadioButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        FilteSettingsTabbedPane.addTab("Precursor relative mass ratio filter settings", precRelMassFilterPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 369, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(FilteSettingsTabbedPane))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(FilteSettingsTabbedPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane FilteSettingsTabbedPane;
    private javax.swing.JButton addMassButton;
    private javax.swing.JLabel addMassLabel;
    private javax.swing.JTextField addMassTextField;
    private javax.swing.JButton addPrecRelMassButton;
    private javax.swing.JLabel addPrecRelMassLabel;
    private javax.swing.JTextField addPrecRelMassTextField;
    private javax.swing.JRadioButton andRadioButton;
    private javax.swing.JLabel filterTypeLabel;
    private javax.swing.ButtonGroup filterTypeRadioButtonGroup;
    private javax.swing.JList massFilterList;
    private javax.swing.JPanel massFilterPanel;
    private javax.swing.JScrollPane massFilterScrollPane;
    private javax.swing.JLabel massToleranceLabel;
    private javax.swing.JTextField massToleranceTextField;
    private javax.swing.JPanel noiseFilterPanel;
    private javax.swing.JRadioButton orRadioButton;
    private javax.swing.JRadioButton precRelAndRadioButton;
    private javax.swing.JLabel precRelFilterTypeLabel;
    private javax.swing.ButtonGroup precRelFilterTypeRadioButtonGroup;
    private javax.swing.JList precRelMassFilterList;
    private javax.swing.JPanel precRelMassFilterPanel;
    private javax.swing.JScrollPane precRelMassFilterScrollPane;
    private javax.swing.JLabel precRelMassToleranceLabel;
    private javax.swing.JTextField precRelMassToleranceTextField;
    private javax.swing.JRadioButton precRelOrRadioButton;
    private javax.swing.JButton removeMassButton;
    private javax.swing.JButton removePrecRelMassButton;
    private javax.swing.JLabel winsorConstantLabel;
    private javax.swing.JTextField winsorConstantTextField;
    private javax.swing.JLabel winsorConvergenceCriterionLabel;
    private javax.swing.JTextField winsorConvergenceCriterionTextField;
    private javax.swing.JCheckBox winsorFilterCheckBox;
    private javax.swing.JLabel winsorOutlierLimitLabel;
    private javax.swing.JTextField winsorOutlierLimitTextField;
    // End of variables declaration//GEN-END:variables
}
