/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.compomics.spectrawl.gui;

/**
 *
 * @author niels
 */
public class SpectrawlGui extends javax.swing.JFrame {

    /**
     * Creates new form SpectrawlGui
     */
    public SpectrawlGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        filtersTabbedPane = new javax.swing.JTabbedPane();
        processFilterParentPanel = new javax.swing.JPanel();
        analyzeFilterParentPanel = new javax.swing.JPanel();
        experimentLoaderParentPanel = new javax.swing.JPanel();
        experimentBinsParentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 5, 0};
        layout.rowHeights = new int[] {0, 10, 0};
        getContentPane().setLayout(layout);

        filtersTabbedPane.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout processFilterParentPanelLayout = new javax.swing.GroupLayout(processFilterParentPanel);
        processFilterParentPanel.setLayout(processFilterParentPanelLayout);
        processFilterParentPanelLayout.setHorizontalGroup(
            processFilterParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 109, Short.MAX_VALUE)
        );
        processFilterParentPanelLayout.setVerticalGroup(
            processFilterParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 253, Short.MAX_VALUE)
        );

        filtersTabbedPane.addTab("process filter", processFilterParentPanel);

        javax.swing.GroupLayout analyzeFilterParentPanelLayout = new javax.swing.GroupLayout(analyzeFilterParentPanel);
        analyzeFilterParentPanel.setLayout(analyzeFilterParentPanelLayout);
        analyzeFilterParentPanelLayout.setHorizontalGroup(
            analyzeFilterParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 109, Short.MAX_VALUE)
        );
        analyzeFilterParentPanelLayout.setVerticalGroup(
            analyzeFilterParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 253, Short.MAX_VALUE)
        );

        filtersTabbedPane.addTab("analyze filter", analyzeFilterParentPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(filtersTabbedPane, gridBagConstraints);

        experimentLoaderParentPanel.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout experimentLoaderParentPanelLayout = new javax.swing.GroupLayout(experimentLoaderParentPanel);
        experimentLoaderParentPanel.setLayout(experimentLoaderParentPanelLayout);
        experimentLoaderParentPanelLayout.setHorizontalGroup(
            experimentLoaderParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );
        experimentLoaderParentPanelLayout.setVerticalGroup(
            experimentLoaderParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.75;
        gridBagConstraints.weighty = 0.15;
        getContentPane().add(experimentLoaderParentPanel, gridBagConstraints);

        experimentBinsParentPanel.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout experimentBinsParentPanelLayout = new javax.swing.GroupLayout(experimentBinsParentPanel);
        experimentBinsParentPanel.setLayout(experimentBinsParentPanelLayout);
        experimentBinsParentPanelLayout.setHorizontalGroup(
            experimentBinsParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );
        experimentBinsParentPanelLayout.setVerticalGroup(
            experimentBinsParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 238, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.75;
        gridBagConstraints.weighty = 0.75;
        getContentPane().add(experimentBinsParentPanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SpectrawlGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SpectrawlGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SpectrawlGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SpectrawlGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SpectrawlGui().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel analyzeFilterParentPanel;
    private javax.swing.JPanel experimentBinsParentPanel;
    private javax.swing.JPanel experimentLoaderParentPanel;
    private javax.swing.JTabbedPane filtersTabbedPane;
    private javax.swing.JPanel processFilterParentPanel;
    // End of variables declaration//GEN-END:variables
}
